### ISSUE TITLE
Elaborar la Maquetación de la App con navegabilidad

### ISSUE THREAD

**Issue by cajalmarcelo** [TinchoGarcia/2023-Mobile-Proyecto-Integrador#21]
Se puede presentar maquetación en Figma y principalmente navegabilidad el Proyecto de Android Studio (paso previo sin funcionalidad).
Incluir una pantalla para contacto.
Incorporar la navegabilidad de la aplicación completa

**Comment by sfrassa** [comment]
Se puede presentar maquetación en Figma y principalmente navegabilidad el Proyecto de Android Studio (paso previo sin funcionalidad).
Incluir una pantalla para contacto.
Incorporar la navegabilidad de la aplicación completa

**Comment by sfrassa** [comment]
Para la maquetación se tuvieron en cuenta las US de los requerimientos: 
#6 US1
#7 US2
#8 US3 
#9 US4
#10 US5
#11 US6

**Comment by sfrassa** [comment]
Se migra la maquetación a un proyecto de Angular Studio que incluye la Navegabilidad.
